#########################################################
# Run Mr Coxall's ICS2O GitHub Action against code base #
#########################################################

---
name: Mr Coxall's ICS2O GitHub Action
on: push

jobs:
  run-linters:
    name: Mr Coxall's ICS2O GitHub Action
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@master

      - name: Build JSDocs
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./js
          output_dir: ./out
          template: minami
          front_page: README.md

      - name: Deploy JSDocs
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./out
        
      - name: Run GitHub Super Linter
        uses: github/super-linter@main
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVASCRIPT_STANDARD: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}